import type { IconNode } from 'lucide';
import {
  AlertTriangle,
  ArrowLeft,
  BookOpen,
  Bookmark,
  Calendar,
  ChartColumn,
  Check,
  ChevronRight,
  Circle,
  Clock,
  Cloud,
  Crosshair,
  Eye,
  FileText,
  Gamepad2,
  Home,
  Info,
  Layers,
  Link,
  LogOut,
  Mail,
  Map,
  Menu,
  Minus,
  Newspaper,
  Package,
  Plus,
  Radar,
  ScanLine,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Tag,
  Target,
  User,
  Wrench,
  Zap,
} from 'lucide';
import type { IconName } from './icons';

export const iconMap: Record<IconName, IconNode> = {
  target: Target,
  settings: Settings,
  map: Map,
  gamepad: Gamepad2,
  'file-text': FileText,
  wrench: Wrench,
  chart: ChartColumn,
  loadout: Package,
  crosshair: Crosshair,
  extraction: LogOut,
  enemy: ShieldCheck,
  movement: Zap,
  loot: Package,
  guide: BookOpen,
  check: Check,
  plus: Plus,
  minus: Minus,
  menu: Menu,
  'chevron-right': ChevronRight,
  'chevron-left': ArrowLeft,
  status: Circle,
  scan: ScanLine,
  cloud: Cloud,
  shield: Shield,
  calendar: Calendar,
  clock: Clock,
  user: User,
  mail: Mail,
  home: Home,
  newspaper: Newspaper,
  'arrow-left': ArrowLeft,
  eye: Eye,
  radar: Radar,
  zap: Zap,
  tag: Tag,
  share: Share2,
  bookmark: Bookmark,
  layers: Layers,
  alert: AlertTriangle,
  info: Info,
  link: Link,
};

export function getIconNode(name: IconName): IconNode {
  return iconMap[name] ?? FileText;
}
