export const SITE = {
  name: 'ArcRaidersCheats',
  title: 'ARC Raiders Cheats — Aimbot, Wallhack',
  description:
    'ARC Raiders cheats & hacks with aimbot, wallhack ESP, loot radar, and 2D extraction intel. Xray, Pro & Private tiers updated after major patches.',
  url: 'https://arcraiderscheats.co',
  locale: 'en_US',
  author: 'ArcRaidersCheats',
  twitter: '@arcraiderscheats',
  logo: '/logo.png',
  logoAlt: 'Arc Raiders Cheats',
  themeColor: '#14b8a6',
  updated: '2026-06-29',
  rating: 'general',
} as const;

export const SITE_KEYWORDS = [
  'arc raiders cheats',
  'arc raiders cheat',
  'arc raiders hack',
  'arc raiders hacks',
  'arc raiders esp',
  'arc raider esp',
  'arc raiders aimbot',
  'arc raider aimbot',
  'arc raiders wallhack',
  'arc raiders radar hack',
  'arc raiders 2d radar',
  'arc raiders loot esp',
  'arc raiders extraction esp',
  'arc raiders no recoil',
  'arc raiders undetected',
  'arc raiders external cheat',
  'arc raiders cheat 2026',
  'arc raiders hacks 2026',
  'arc raiders private cheat',
  'arc raiders vip cheat',
  'arc raiders xray cheat',
  'arc raiders pro cheat',
  'arc raiders hwid spoofer',
  'arc raiders cloud dma',
  'skin changer',
  'unlock weapon skins',
  'game skin unlocker',
  'arcraiderscheats',
  'buy arc raiders cheat',
  'arc raiders cheat buy',
  'arc raiders cheat price',
  'arc raiders cheat download',
  'arc raiders cheat provider',
  'arc raiders cheat software',
  'arc raiders cheat menu',
  'arc raiders cheat loader',
  'arc raiders premium cheat',
  'arc raiders legit cheat',
  'arc raiders rage cheat',
  'arc raiders internal cheat',
  'arc raiders kernel cheat',
  'arc raiders overlay cheat',
  'arc raiders dma cheat',
  'arc raiders triggerbot',
  'arc raiders wallhack esp',
  'arc raiders pvp cheat',
  'arc raiders pve cheat',
  'arc raiders extraction hack',
  'arc raiders loot hack',
  'arc raiders bot esp',
  'arc raiders arc esp',
  'arc raiders arc bot esp',
  'arc raiders patrol esp',
  'arc raiders radar esp',
  'arc raiders stream proof cheat',
  'arc raiders stream safe cheat',
  'arc raiders undetected hack',
  'arc raiders easy anti cheat bypass',
  'arc raiders anti cheat bypass',
  'arc raiders eac bypass',
  'arc raiders eac',
  'arc raiders embark cheat',
  'arc raiders embark studios cheat',
  'arc raiders player esp',
  'arc raiders skeleton esp',
  'arc raiders drone esp',
  'arc raiders health esp',
  'arc raiders distance esp',
  'arc raiders loot tracker',
  'arc raiders extraction radar',
  'arc raiders bone aimbot',
  'arc raiders silent aimbot',
  'arc raiders aim assist',
  'arc raiders recoil control',
  'arc raiders no spread',
  'arc raiders hwid reset',
  'arc raiders spoofer',
  'arc raiders viper cheat',
  'arc raiders cold snap cheat',
  'best arc raiders cheat 2026',
  'arc raiders aimbot 2026',
  'arc raiders season 1 cheat',
  'arc raiders season 2 cheat',
] as const;

export const SITE_FONT = {
  family: 'Inter Variable',
  preload: '/fonts/inter-latin.woff2',
} as const;

export const SITE_LOGO_URL = `${SITE.url}${SITE.logo}`;

/** Checkout / access affiliate link */
export const GET_ACCESS_URL = 'https://zadeyo.com/go/PRO?to=/products/arc-raiders-cheats';

/** Contact, support, Discord, and other external help links — same ref */
export const CONTACT_URL = GET_ACCESS_URL;

export const NAV_LINKS = [
  { href: '/cheats/', label: 'Cheats' },
  { href: '/products/', label: 'Products' },
  { href: '/blog/', label: 'Blog' },
  { href: '/faq/', label: 'FAQ' },
  { href: '/about/', label: 'About' },
] as const;
